Fix the legacy driver path construction on non-Windows platforms
swiftlang/swift-driver pull request #1756
Opened 2024-12-11 15:47 UTC by kateinoigakukun

`swift-driver` tries to invoke `swiftc-legacy-driver.` (trailing dot) on non-Windows platforms when legacy driver is requested since https://github.com/swiftlang/swift-driver/pull/1746

This is because `URL.pathExtension` returns an empty string if the URL does not have an extension but `URL.appendPathExtension` appends a period before the extension even if given an empty string. Thus `url.deletingPathExtension().appendingPathExtension(url.pathExtension)` will not be equal to `url` if `url` does not have an extension.

2024-12-11 15:47 UTC, kateinoigakukun commented
@swift-ci test

2024-12-11 15:59 UTC, kateinoigakukun commented
Wait, it seems like a swift-foundation side issue:
```swift
import Foundation
let url = URL(fileURLWithPath: "/tmp/x")
print(url.deletingPathExtension().appendingPathExtension(url.pathExtension))
// Swift 5.10: file:///tmp/x
// Swift 6.0: file:///tmp/x.
```

2024-12-12 04:45 UTC, kateinoigakukun commented
@compnerd The team said it was an unintentional change and fixed in the main branch. https://github.com/swiftlang/swift-foundation/issues/1080

2024-12-12 04:46 UTC, kateinoigakukun commented
@swift-ci smoke test

2024-12-12 14:39 UTC, kkebo commented on Sources/swift-driver/main.swift
> +    // extension.on Swift 6.0. Remove this when we drop support for Swift 6.0
A typo?

```suggestion
    // extension on Swift 6.0. Remove this when we drop support for Swift 6.0
```

2024-12-12 15:52 UTC, compnerd requested changes

2024-12-12 15:52 UTC, compnerd commented on Sources/swift-driver/main.swift
> +    var legacyExecutablePath: URL =
Can you duplicate this code instead and guard it with a compiler version check please?

2024-12-12 16:45 UTC, kateinoigakukun commented on Sources/swift-driver/main.swift
> +    var legacyExecutablePath: URL =
Ok, gated behind 6.2 until we cherry-pick the fix to 6.1 branch.

2024-12-13 21:31 UTC, compnerd commented
@swift-ci please test macOS platform

2024-12-13 21:48 UTC, compnerd commented
@swift-ci please test Windows platform

2024-12-14 04:33 UTC, merged